apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kproximate.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kproximate.fullname" . }}
  apiGroup: ""
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kproximate.fullname" . }}
  apiGroup: ""