kproximate:
  config:
    debug: true
    # Set to match your actual node cores
    kpNodeCores: 4
    # Set to match your actual node memory in MiB (4GB = 4096 MiB)
    kpNodeMemory: 4096
    kpNodeNamePrefix: kp-node
    kpNodeTemplateName: ubuntu-22.04-cloudinit-template
    kpNodeLabels: "topology.kubernetes.io/region=proxmox-cluster,topology.kubernetes.io/zone={{ .TargetHost }}"
    # Increase headroom to prevent rapid scale up/down cycles
    loadHeadroom: 0.3
    # Adjust based on your Proxmox capacity
    maxKpNodes: 4
    kpLocalTemplateStorage: true
    pmUrl: https://proxmox.example.com:8006/api2/json
    pmUserID: kproximate@pam!kproximate
    kpQemuExecJoin: true
    # Increase wait times to allow nodes to fully join
    waitSecondsForJoin: 600
    waitSecondsForProvision: 600

    # Node selection strategy for scaling up. Options: spread, max-memory, max-cpu, balanced, round-robin
    # if not set, defaults to "spread"
    nodeSelectionStrategy: "balanced"

    # Minimum available CPU cores required for a host to be eligible for scaling up
    # Set to 0 to disable CPU-based filtering
    minAvailableCpuCores: 2

    # Minimum available memory in MB required for a host to be eligible for scaling up
    # Set to 0 to disable memory-based filtering
    minAvailableMemoryMB: 8192

    # Comma-separated list of Proxmox node names to exclude from scaling up
    # Useful for maintenance, dedicated workloads, or resource constraints
    excludedNodes: "proxmox-node-maintenance,proxmox-node-storage"

  secrets:
    pmToken: token-here
    kpJoinCommand: |
      curl --proto '=https' --tlsv1.2 -sSf https://get.k0s.sh | sudo K0S_VERSION=v1.33.1+k0s.0 sh
      JOIN_TOKEN="------"
      echo $JOIN_TOKEN > /tmp/join-token
      sudo k0s install worker --token-file /tmp/join-token
      sudo k0s start

workerReplicaCount: 1

rabbitmq:
  auth:
    password: password
