# Example configuration demonstrating different node selection strategies
# and resource restrictions for Proxmox node selection

kproximate:
  config:
    # Basic node configuration
    kpNodeCores: 4
    kpNodeMemory: 4096
    kpNodeNamePrefix: kp-node
    kpNodeTemplateName: ubuntu-22.04-cloudinit-template
    kpNodeLabels: "topology.kubernetes.io/region=proxmox-cluster,topology.kubernetes.io/zone={{ .TargetHost }}"
    loadHeadroom: 0.3
    maxKpNodes: 6
    kpLocalTemplateStorage: true
    pmUrl: https://proxmox.example.com:8006/api2/json
    pmUserID: kproximate@pam!kproximate
    kpQemuExecJoin: true
    waitSecondsForJoin: 600
    waitSecondsForProvision: 600

    # Node Selection Strategy Configuration
    # Available strategies:
    # - "spread": Distributes nodes across different Proxmox hosts (default)
    # - "max-memory": Selects host with most available memory
    # - "max-cpu": Selects host with most available CPU
    # - "balanced": Selects host with best combined CPU and memory availability
    # - "round-robin": Cycles through available hosts
    nodeSelectionStrategy: "balanced"

    # Resource Restrictions
    # Minimum available CPU cores required for a host to be eligible for scaling up
    # Set to 0 to disable CPU-based filtering
    minAvailableCpuCores: 2

    # Minimum available memory in MB required for a host to be eligible for scaling up
    # Set to 0 to disable memory-based filtering
    minAvailableMemoryMB: 8192  # 8GB

    # Comma-separated list of Proxmox node names to exclude from scaling up
    # Useful for maintenance, dedicated workloads, or resource constraints
    excludedNodes: "proxmox-node-maintenance,proxmox-node-storage"

  secrets:
    pmToken: <proxmox-api-token>
    sshKey: <ssh-public-key>

rabbitmq:
  auth:
    password: <set-rabbitmq-password-here>

---
# Alternative configuration examples:

# Example 1: Spread strategy with basic resource filtering
# kproximate:
#   config:
#     nodeSelectionStrategy: "spread"
#     minAvailableCpuCores: 1
#     minAvailableMemoryMB: 4096
#     excludedNodes: ""

# Example 2: Max memory strategy for memory-intensive workloads
# kproximate:
#   config:
#     nodeSelectionStrategy: "max-memory"
#     minAvailableCpuCores: 0
#     minAvailableMemoryMB: 16384  # 16GB minimum
#     excludedNodes: "small-node-1,small-node-2"

# Example 3: Round-robin for even distribution
# kproximate:
#   config:
#     nodeSelectionStrategy: "round-robin"
#     minAvailableCpuCores: 2
#     minAvailableMemoryMB: 8192
#     excludedNodes: ""

# Example 4: Max CPU strategy for CPU-intensive workloads
# kproximate:
#   config:
#     nodeSelectionStrategy: "max-cpu"
#     minAvailableCpuCores: 4
#     minAvailableMemoryMB: 4096
#     excludedNodes: "gpu-node-1,gpu-node-2"  # Exclude specialized nodes
